/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CardBase: typeof import('./src/components/CardBase.vue')['default']
    ModeToggler: typeof import('./src/components/ModeToggler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBase: typeof import('./src/components/sections/SectionBase.vue')['default']
    SectionCards: typeof import('./src/components/sections/SectionCards.vue')['default']
    SectionPokemons: typeof import('./src/components/sections/SectionPokemons.vue')['default']
    SectionText: typeof import('./src/components/sections/SectionText.vue')['default']
    Stack: typeof import('./src/components/ui/Stack.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VMain: typeof import('vuetify/lib')['VMain']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
