/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBase: typeof import('./src/components/sections/SectionBase.vue')['default']
    SectionCards: typeof import('./src/components/sections/SectionCards.vue')['default']
    SectionPokemons: typeof import('./src/components/sections/SectionPokemons.vue')['default']
    SectionText: typeof import('./src/components/sections/SectionText.vue')['default']
    Stack: typeof import('./src/components/ui/Stack.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VImg: typeof import('vuetify/lib')['VImg']
    VInput: typeof import('vuetify/lib')['VInput']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTitle: typeof import('vuetify/lib')['VTitle']
  }
}
